init dev branch
smmhubru/java-explore-with-me pull request #1
Opened 2022-09-29 07:14 UTC by smmhubru

2022-10-13 14:19 UTC, db-exp commented on docs/DDD-main-service
> +@startuml
Респект за использование uml!

2022-10-13 17:00 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/CompilationRepository.java
> +public interface CompilationRepository extends JpaRepository<Compilation, Long> {
Нужно добавить аннотацию @repository

2022-10-13 17:03 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/CompilationService.java
> +public class CompilationService {
Лучше пробрасывать свою ошибку, а на уровне глобального обработчика уже отдавать ошибку слоя контроллера -  относится ко всем методам ниже

2022-10-13 17:06 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/dto/NewCompilationDto.java
> +    private String title;
Нужно добавить валидацию @size

2022-10-13 17:07 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/event/Event.java
> +public class Event {
Нужно добавить @Size на String поля

2022-10-13 17:13 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/event/EventController.java
> +    @GetMapping("/admin/events")
тут и в методах ниже с /admin - их нужно вынести в отдельный контроллер, плохая практика смешивать разные по назначению API

2022-10-13 17:15 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/event/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long> {
нужно добавить аннотацию @repository

2022-10-13 17:18 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/event/EventService.java
> +public class EventService {
Ошибки из методов должны кидаться свои - не уровня контроллера, а уже на уровне глобального обработчика превращаться в пользовательские

2022-10-13 17:24 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/event/dto/NewEventDto.java
> +public class NewEventDto {
Нужно добавить @Size на String поля

2022-10-13 17:25 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/event/dto/UpdateEventDto.java
> +public class UpdateEventDto {
Нужно добавить @Size на String поля

2022-10-13 17:31 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/event/dto/AdminUpdateEventDto.java
> +public class AdminUpdateEventDto {
Нужно добавить валидацию @Size на String поля

2022-10-13 17:32 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/participation/ParticipationRequestController.java
> +public class ParticipationRequestController {
Корневой маппинг /users лучше перенести сюда

2022-10-13 17:42 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/participation/ParticipationRequestService.java
> +public class ParticipationRequestService {
Тут как и выше - лучше ошибки переделать

2022-10-13 17:44 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/participation/PersistentParticipationRequestStorage.java
> +            return Optional.of(participationRequestRepository.save(request));
save не должен выдавать ошибку - если такое есть, то это либо недостаток валидации, либо системные проблемы - БД отвалилась например.

2022-10-13 17:46 UTC, db-exp commented on stat_service/src/main/java/ru/practicum/statservice/app/EndpointHitService.java
> +public class EndpointHitService {
Как и выше - лучше поменять ошибки

2022-10-13 17:47 UTC, db-exp commented on stat_service/src/main/java/ru/practicum/statservice/app/EndpointHitService.java
> +        } catch (Exception ex) {
ловить все в этом случае не нужно и плохая практика - тут ошибка парсинга даты

2022-10-13 17:47 UTC, db-exp commented on stat_service/src/main/java/ru/practicum/statservice/app/EndpointHitService.java
> +            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
формат даты лучше вынести в константу

2022-10-13 17:48 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/user/PersistentUserStorage.java
> +        } catch (Exception ex) {
save не нужно оборачивать в try/catch

2022-10-13 17:49 UTC, db-exp commented on stat_service/src/main/java/ru/practicum/statservice/app/PersistentEndpointHitStorage.java
> +        } catch (Exception ex) {
save не нужно оборачивать в try/catch

2022-10-13 17:51 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/user/User.java
> +public class User {
Нужно добавить валидацию @Size на String поля

2022-10-13 17:52 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/user/UserService.java
> +public class UserService {
Тут как и выше - лучше ошибки переделать

2022-10-13 17:53 UTC, db-exp commented on stat_service/src/main/java/ru/practicum/statservice/app/EndpointHit.java
> +public class EndpointHit {
Нужно добавить валидацию @Size на String поля

2022-10-13 17:57 UTC, db-exp commented on stat_service/src/main/java/ru/practicum/statservice/validator/ValidationErrorHandler.java
> +public class ValidationErrorHandler {
Сюда можно добавить как раз обработку кастомной ошибки из сервисов и выдавать bad request итп

2022-10-14 04:25 UTC, smmhubru commented on docs/DDD-main-service
> +@startuml
спасибо

2022-10-14 04:33 UTC, smmhubru commented on main_service/Dockerfile
> +RUN mvn -f /home/app/pom.xml clean install -Dmaven.test.skip
fixed

2022-10-14 05:05 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/category/Category.java
> +    private String name;
fixed

2022-10-14 05:06 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/category/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
fixed

2022-10-14 05:08 UTC, smmhubru commented on stat_service/src/main/java/ru/practicum/statservice/app/dto/EndpointHitDto.java
> +public class EndpointHitDto {
fixed

2022-10-14 05:09 UTC, smmhubru commented on stat_service/src/main/java/ru/practicum/statservice/app/EndpointHitRepository.java
> +public interface EndpointHitRepository extends JpaRepository<EndpointHit, Long> {
fixed

2022-10-14 05:15 UTC, smmhubru commented on stat_service/pom.xml
> +			<version>3.1.0</version>
fixed

2022-10-14 05:16 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/user/dto/NewUserDto.java
> +    private String name;
fixed

2022-10-14 05:16 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/user/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
fixed

2022-10-14 05:33 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/user/UserController.java
> +    @GetMapping("/admin/users")
fixed

2022-10-14 05:34 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/participation/ParticipationRequestRepository.java
> +public interface ParticipationRequestRepository extends JpaRepository<ParticipationRequest, Long> {
fixed

2022-10-14 05:36 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/category/CategoryController.java
> +public class CategoryController {
адреса в контроллере разнородные

2022-10-14 05:39 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/Compilation.java
> +    private String title;
fixed

2022-10-14 05:40 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/CompilationController.java
> +    @GetMapping("/compilations")
адреса разнородные

2022-10-14 05:47 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/CompilationController.java
> +    @PostMapping("/admin/compilations")
fixed

2022-10-14 05:56 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/dto/NewCompilationDto.java
> +    private String title;
fixed

2022-10-14 06:00 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/event/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long> {
fixed

2022-10-14 06:49 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/category/CategoryController.java
> +public class CategoryController {
fixed

2022-10-14 06:49 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/CompilationController.java
> +    @GetMapping("/compilations")
fixed

2022-10-14 06:49 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/CompilationRepository.java
> +public interface CompilationRepository extends JpaRepository<Compilation, Long> {
fixed

2022-10-14 06:50 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/event/Event.java
> +public class Event {
Валидация вынесена в DTO, fixed

2022-10-14 06:51 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/event/EventController.java
> +    @GetMapping("/admin/events")
fixed

2022-10-14 06:51 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/event/dto/NewEventDto.java
> +public class NewEventDto {
fixed

2022-10-14 06:52 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/event/dto/UpdateEventDto.java
> +public class UpdateEventDto {
fixed

2022-10-14 06:54 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/event/dto/AdminUpdateEventDto.java
> +public class AdminUpdateEventDto {
fixed, хотя в тз было указано, что на админский ручке валидация должна быть отключена: _«Редактирование данных любого события администратором. Валидация данных не требуется.»_

2022-10-14 06:58 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/participation/ParticipationRequestController.java
> +public class ParticipationRequestController {
fixed

2022-10-14 07:00 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/participation/PersistentParticipationRequestStorage.java
> +            return Optional.of(participationRequestRepository.save(request));
save выдает ошибку в случае нарушения ограничений БД, в данном случае уникальность связки (event_id и request_id), в этом случае возвращается пустой опционал, который ловится исключением и формирует 409 ошибку.

2022-10-14 07:03 UTC, smmhubru commented on stat_service/src/main/java/ru/practicum/statservice/app/EndpointHitService.java
> +            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
fixed

2022-10-14 07:04 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/user/PersistentUserStorage.java
> +        } catch (Exception ex) {
В данном случае возникнет исключение в случае нарушения ограничения базы на уникальность поля email.

2022-10-14 07:05 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/user/User.java
> +public class User {
валидация вынесена на DTO, fixed

2022-10-14 07:06 UTC, smmhubru commented on stat_service/src/main/java/ru/practicum/statservice/app/EndpointHit.java
> +public class EndpointHit {
Валидация вынесена в DTO, fixed

2022-10-14 10:28 UTC, db-exp requested changes

2022-10-14 10:28 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/category/Category.java
> +    private String name;
Размерность не вижу 
@Column(unique = true)
    private String name;

2022-10-14 10:28 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/category/CategoryController.java
> +public class CategoryController {
Не вижу изменений

2022-10-14 10:28 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/compilation/Compilation.java
> +    private String title;
не вижу изменений

2022-10-14 10:28 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/event/EventController.java
> +public class EventController {
Здесь стоит разнести методы - есть и /events и /users

2022-10-14 10:28 UTC, db-exp commented on main_service/src/main/java/ru/practicum/explorewithme/event/dto/UpdateEventDto.java
> +public class UpdateEventDto {
остался еще title

2022-10-14 10:28 UTC, db-exp commented on pom.xml
> +	<dependencies>
Нужно  <dependencyManagement> использовать в корневом и уже 
<dependency>
			<groupId>org.modelmapper</groupId>
			<artifactId>modelmapper</artifactId>
</dependency>

в поме сервиса

2022-10-15 04:32 UTC, smmhubru commented on main_service/src/main/java/ru/practicum/explorewithme/event/EventController.java
> +public class EventController {
Классы `Category.java`, `Compilation.java` не используются для валидация, это сущности для создания соответствующих таблиц в хранилище. Валидация вынесена на соответствующие DTO: `NewCategoryDto`, `UpdateCategoryDto`, `NewCompilationDto`. Там присутствуют: `@NotNull`, `@NotBlank` и `@Size`. Hibernate по умолчанию, если мне память не изменяет, вешает ограничение 255 символов на эти колонки при создании по дефолту. OnCreate и OnUpdate группы валидация выпилены из проекта в пользу соответствующих DTO.

При разнесении методов по контроллерам я руководствуюсь доменными областями и возвращаемыми сущностями, если ручка начинается на `/users/`, но возвращает `EventFullDto` (например, `/users/{userId}/events/{eventId}` -- ей вполне логично находиться находиться в домене `event`). К сожалению, в  проекте нам не предоставлена свобода определения ручек, поскольку явно ручка должна была иметь адрес `/events/{eventId}/users/{userId}`

2022-10-15 04:53 UTC, smmhubru commented on pom.xml
> +	<dependencies>
fixed

2022-10-15 07:32 UTC, db-exp approved these changes

2022-10-15 11:42 UTC, merged